name: component tests
on:
  workflow_dispatch:
  push:
    paths:
      - 'components/**'
      - 'components-map/**'
      - 'storybook/**'
    branches:
      - main
  pull_request:
    paths:
      - 'components/**'
      - 'components-map/**'
      - 'storybook/**'
    types: [opened, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./storybook
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run test-storybook:ci
